### ISSUE TITLE
HU-007-TA-01 Crear página de planes disponibles

### ISSUE THREAD

**Issue by MarcoPavez** [MarcoPavez/Indice-Diario#19]
Construir sólo las cartas de los planes. El navbar y el footer serán construidos en el futuro y se integrarán como componentes de React.

Las cartas de los planes se encuentran en el frame "PLANES" en el siguiente link de Figma: [Figma Índice Diario](https://www.figma.com/file/sWJNi9pD6EHVHBTAbjNBsH/Gu%C3%ADa-de-estilos-y-mockups-%C3%8Dndice-Diario?node-id=0%3A1&t=9pHTQsqutB3gbbyh-1)

**Comment by CynthMartz** [comment]
Terminado, aunque tengo dudas sobre algunos estilos que utilizé.

**Comment by MarcoPavez** [comment]
> Terminado, aunque tengo dudas sobre algunos estilos que utilizé.

Hola Cynthia, ¿podrías hacer un git push para que se cree el pull request y así revisar tus cambios? Quedo atento, gracias por tu trabajo.
